In [9]:
import matplotlib.pyplot as plt

import pandas as pd
data=pd.read_csv('C:/Users/USER/Google Drive/stage/samples.csv')
data

,'Elapsed time','i','ii','iii','avr','avl','avf','v1','v2','v3','v4','v5','v6','vx','vy','vz'
0,'hh:mm:ss.mmm','mV','mV','mV','mV','mV','mV','mV','mV','mV','mV','mV','mV','mV','mV','mV'
1,'0:10.000',0.030,0.047,0.017,-0.038,0.006,0.032,-0.074,-0.091,0.001,0.057,0.053,0.068,0.037,0.194,-0.083
2,'0:10.001',0.036,0.056,0.019,-0.046,0.009,0.037,-0.085,-0.098,-0.003,0.053,0.051,0.068,0.039,0.200,-0.079
3,'0:10.002',0.028,0.060,0.033,-0.043,-0.003,0.046,-0.092,-0.100,0.003,0.059,0.057,0.074,0.040,0.198,-0.075
4,'0:10.003',0.030,0.059,0.029,-0.044,0.001,0.043,-0.113,-0.107,-0.001,0.058,0.054,0.073,0.043,0.191,-0.070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,'0:19.995',0.079,0.084,0.005,-0.082,0.037,0.044,0.038,0.193,0.171,0.052,0.007,-0.009,0.007,-0.057,-0.004
9997,'0:19.996',0.082,0.080,-0.002,-0.082,0.042,0.040,0.033,0.181,0.163,0.052,0.007,-0.011,0.010,-0.059,-0.005
9998,'0:19.997',0.078,0.083,0.006,-0.081,0.036,0.044,0.035,0.178,0.161,0.051,0.008,-0.009,0.009,-0.054,-0.007
9999,'0:19.998',0.068,0.088,0.021,-0.079,0.024,0.054,0.040,0.176,0.160,0.052,0.013,-0.005,0.005,-0.057,-0.006
10000,'0:19.999',0.058,0.090,0.033,-0.074,0.013,0.061,0.047,0.180,0.164,0.060,0.022,0.002,0.006,-0.050,-0.005